[package]
name = "sw_listener"
version = "0.4.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "swl_lib"
path = "src/lib.rs"

[dependencies]
quinn = "*"
rustls = { version = "*", features = ["quic"] }
tokio = { version = "1.13.0", features = ["full"] }
rcgen = "0.10.0"
directories-next = "2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
actix-web = "4"
futures = "0.3.30"
lazy_static = "1.4.0"
tracing = "0.1.40"
tracing-futures = "0.2.5"
webpki = "0.22.4"
openssl = "0.10.64"
